config/routes.rb
Rails.application.routes.draw do
  resources :favorite_beers, only: [:index, :create, :destroy]
  resources :added_breweries, only: [:index, :create, :destroy]


  devise_for :users, controllers: { registrations: "registrations" }
  get 'users/new' # NHO: is this route necessary?
  resources :breweries do
    resources :beers do
      resources :reviews
    end
  end

  root 'home#index'

end

app/controllers/added_breweries_controller.rb
class AddedBreweriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @breweries = current_user.added_breweries
  end

  def create
    @brewery = Brewery.find(params[:brewery_id])
    @add = Add.create(added: @brewery, user: current_user)
    @add.brewery_id = @brewery.id # NHO: is this line necessary?
    if @add.save
      redirect_to @brewery, notice: 'added to your route!'
    else
      redirect_to @brewery # NHO: could display a notice saying it was unsuccessful...
    end
  end

  def destroy
    @brewery = Brewery.find(params[:id])
    @add = Add.where(added_id: @brewery.id, user: current_user).first.destroy
    if @add.destroy
      redirect_to @brewery, notice: 'removed from your route!'
    else
      redirect_to @brewery
    end
  end
end

app/helpers/added_breweries_helper.rb
module AddedBreweriesHelper
end

app/views/added_breweries/index.html.erb
<h2> Your Current Brewery Route:</h2>

<% if current_user.added_breweries.exists? -%>
<ul class = "added_breweries"><% @breweries.each do |brewery| %>
  <li><div class = "fav_brewery">
    <li>  <a href="/breweries/<%= brewery.id %>"> <%= brewery.name %> - <%brewery.address%></li>
    </a>
  </div></li>

  <%end%>
</ul>
<%else%>
<h3>There are no breweries on your route at this time. Fix this by clicking the "(+) add to route" next to the Brewery page headings!</h3>
<%end%>
<%=link_to "Back to All Breweries", breweries_path%>