config/routes.rb
Rails.application.routes.draw do
  resources :favorite_beers, only: [:index, :create, :destroy]
  resources :added_breweries, only: [:index, :create, :destroy]


  devise_for :users, controllers: { registrations: "registrations" }
  get 'users/new' # NHO: is this route necessary?
  resources :breweries do
    resources :beers do
      resources :reviews
    end
  end

  root 'home#index'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :beers, dependent: :destroy
  geocoded_by :address
  # NHO: could be a great opportunity for a code comment
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  def index
    @breweries = Brewery.all.sample(Brewery.all.length)
  end

  def show
    @brewery = Brewery.find(params[:id])
  end

  def brewery_params
    params.require(:brewery).permit(:name, :address, :latitude, :longitude, :photo_url, :logo_img, :description)
  end

end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/index.html.erb
<h2> Explore Our Brewery Partners:</h2>
<div class="breweries">
  <% @breweries.each do |brewery| %>
<li>  <div class = "brewery">
    <a href="/breweries/<%= brewery.id %>">
      <br>
      <%= brewery.name %>
    </a>
  </div></li>
  <% end %>
</div>

app/views/breweries/show.html.erb
<!-- NHO: careful of indentation  -->
<h2>
  <%=@brewery.name%>
  <%if current_user%>
  <% unless current_user.added_breweries.exists?(id: @brewery.id) %>
  <%=link_to "(+) to route", added_breweries_path(brewery_id: @brewery), method: :post, class: "route"%>
  <% else %>
  <%=link_to "(-) from route", added_brewery_path(@brewery), method: :delete, class: "no-route"%>
  <% end %>
  <% end %>
</h2>

<p><% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<div class = "photo_and_map">
  <%= image_tag(@brewery.photo_url, class: "photo") %>
  <!-- NHO: recommend you use a gem like Figaro or Dotenv to hide your API key! -->
  <%= image_tag "//maps.googleapis.com/maps/api/staticmap?center=#{@brewery.latitude},#{@brewery.longitude}&zoom=13&size=300x300&maptype=roadmap&markers=&markers=#{@brewery.latitude},#{@brewery.longitude}&key=AIzaSyCxxjJpNla-0b8zzZ6pVKVnH4-ftC-2tnE",
  class: 'map', alt: "#{@brewery.name} on the map"%>
</div>

  <%=image_tag(@brewery.logo_img, class: "logo")%>
  <div class = "larger_text"><%=@brewery.description%>
    <p>
      Address: <a href="https://maps.google.com/?q=<%=@brewery.address %>"><%=@brewery.address%></a>
    </p>
    <p>
      Coordinates: <%= @brewery.latitude %> <%= @brewery.longitude %>
    </p>
    </div>

    <h3> Beers by <%=@brewery.name%></h3>
    <ul>
      <% @brewery.beers.each do |beer| %>
      <h3><%= link_to beer.name, brewery_beer_path(@brewery, beer) %> <h3>
        <ul>
          <li> Style: <%= beer.style %> </li>
          <li>  ABV: <%= beer.abv %></li>
          <li> <% if current_user%><% if beer.user == current_user %><%= link_to "edit", edit_brewery_beer_path(@brewery, beer) %> | <%= link_to "delete", [beer.brewery, beer], method: :delete, data:{confirm: 'are you sure?'}%><%end%><%end%></li>
        </ul>
        <% end %>
      </ul>

    <h3><%= link_to "Add another " + @brewery.name + " beer here!", new_brewery_beer_path(@brewery) if current_user%></h3>