config/routes.rb
Rails.application.routes.draw do
  resources :favorite_beers, only: [:index, :create, :destroy]
  resources :added_breweries, only: [:index, :create, :destroy]


  devise_for :users, controllers: { registrations: "registrations" }
  get 'users/new' # NHO: is this route necessary?
  resources :breweries do
    resources :beers do
      resources :reviews
    end
  end

  root 'home#index'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  belongs_to :user
  # NHO: what happened to this functionality? Are you planning on using a polymorhpic relationship?
  # NHO: has_many :favorites, as: :favorited
  # has_many :favorites
  # has_many :users, through: :favorites

  validates :name, presence: true
  validates :style, presence: true
  has_many :reviews, dependent: :destroy
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  # NHO: what lines are repetitive in this controller?
  # You could use a before_action to DRY up the code by writing a method like find_brewery
  def show
    @brewery = Brewery.find(params[:brewery_id])
    @beer = Beer.find(params[:id])
    @review = Review.new
  end

  def new
    redirect_to root_path unless current_user
    @brewery = Brewery.find(params[:brewery_id])
    @beer = Beer.new
  end

  def create
    redirect_to root_path unless current_user
    @brewery = Brewery.find(params[:brewery_id])
    @beer = @brewery.beers.create(beer_params)
    @beer.user_id = current_user.id
    if @beer.save
      redirect_to @brewery
    else
      flash[:alert] = "Please include the beer's name and style"
      redirect_to new_brewery_beer_path
    end
    unless current_user == @beer.user
      redirect_to(root_path, notice: "Sign in to add a beer") and return
    end
  end

  def edit
    @brewery = Brewery.find(params[:brewery_id])
    @beer = Beer.find(params[:id])
    unless current_user == @beer.user
      redirect_to(root_path, notice: "You cannot edit this beer") and return
    end
  end

  def update
    @brewery = Brewery.find(params[:brewery_id])
    @beer = Beer.find(params[:id])
    @beer.update(beer_params)
    if @beer.save(beer_params)
      redirect_to @brewery
    else
      flash[:alert] = "Please include the beer's name and style"
      redirect_to edit_brewery_beer_path
    end
    # NHO: careful of the order here, currently this will still destroy the beer, and then redirect them
    unless current_user == @beer.user# NHO: we need to move this block to the first line of this action
      redirect_to(root_path, notice: "You cannot edit this beer") and return
      @brewery = Brewery.find(params[:brewery_id])
    end
  end

  def destroy
    @brewery = Brewery.find(params[:brewery_id])
    @beer = Beer.find(params[:id])
    @beer.destroy
    redirect_to @brewery

    # NHO: careful of the order here, currently this will still destroy the beer, and then redirect them
    unless current_user == @beer.user # NHO: we need to move this block to the first line of this action
      redirect_to (root_path notice: "You cannot delete this beer") and return
    end
  end

  private
  def beer_params
    params.require(:beer).permit(:name, :style, :abv, :photo_url, :brewery_id)
  end
end

app/views/beers/_form.html.erb
<%= form_for [@brewery, @beer] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :style %>
  <%= f.text_field :style %>

  <%= f.label :abv %>
  <%= f.text_field :abv %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.submit %>

<% end %>

app/views/beers/_new_beer_form.html.erb
<%= form_for [@brewery, @beer] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :style %>
  <%= f.text_field :style %>

  <%= f.label :abv %>
  <%= f.text_field :abv %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.submit %>

<% end %>

app/views/beers/_review_form.erb
<%= form_for ([@brewery, @beer, @review]) do |f| %>

<%= f.hidden_field :user_id, :value => @current_user.id %>

<%= f.label :body %>
<%= f.text_field :body %>

<%= f.submit %>

<% end%>

app/views/beers/edit.html.erb
<h2> Currently editing: <%=@beer.name%> </h2>

<%= render 'form' %>

<p><% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/beers/new.html.erb
<h2>New <%=@brewery.name%> beer:</h2>

<%= render 'form' %>

<p><% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

app/views/beers/show.html.erb
<h2> <%= @beer.name %> <br> style: <%= @beer.style %>  </h2>

<p>
  <%if current_user%>
  <% unless current_user.favorite_beers.exists?(id: @beer.id) -%>
  <%= link_to 'FAVORITE!', favorite_beers_path(beer_id: @beer), method: :post, class: "fav"%>
  <% else %>
  <%= link_to 'NON-FAVORITE!', favorite_beer_path(@beer), method: :delete, class: "no_fav"%>
  <% end %>
  <% end %>
</p>

<div class = "beer_reviews">
  <h3> BEER REVIEWS </h3>

  <% if @beer.reviews.any? %>
  <% @beer.reviews.each do |review| %>
  <div class = "review">
    <!-- NHO: could be a great usecase for Rails' helper method: time_ago_in_words   -->
    <p class = "timestamp">By <%= review.user.name%> at <%= review.created_at%> </p>
    <p><%= review.body%></p>
    <% if review.user == current_user %>
    <li> <%= link_to "edit", edit_brewery_beer_review_path(@brewery, @beer, review) %> | <%= link_to "delete", brewery_beer_review_path(@brewery, @beer, review), method: :delete, data:{confirm: 'are you sure?'} %>  </div>
      <!-- NHO: Careful of your indentation as it can make it harder to maintain, especially view code  -->
      <% end%>
      <% end%>
      <% else %>
      <p> No Reviews Yet!</p>
      <% end %>
    </div>
    <div class = "form">
      <% if current_user %>
      <h3> Write a Review of the <%=@beer.name%>:</h3>
      <%= render 'reviews/review_form' %>
      <% end %>
    </div>
    <p><% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>